# Generated by Django 4.1.4 on 2022-12-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default=('DRAFT', 'Draft'), max_length=16)),
            ],
        ),
    ]
